### ISSUE TITLE
Compatibilité smartphone ?

### ISSUE THREAD

**Issue by Sacramentix** [MrStanDu33/estcequemonordinateurestallume.fr#1]
J'ai un truc qui s'appelle un smartphone et je me demandais si le résultat de ce magnifique site web permet aussi d'indiquer l'état de celui. Seriez-vous en mesure de le dire?

😅

**Comment by arthurmadecprevost** [comment]
Bonjour @Sacramentix 
C'est une bonne question que vous posez là, je me la pose également.
Je pense que l'équipe d'ingénieurs de @MrStanDu33 saura nous répondre.

Bonne soirée à vous,

**Comment by MrStanDu33** [comment]
@Sacramentix @arthurmadecprevost Hold my beer ! 🍺

**Comment by MrStanDu33** [comment]
@Sacramentix @arthurmadecprevost 

Suite à votre requête, l'équipe technique a décidé, avec l'accord du département comptable, d'accéder à votre demande.

Nous sommes donc fiers aujourd'hui de vous présenter le site [estcequemontelephoneestallume.fr](https://estcequemontelephoneestallume.fr). Grâce à ce site, vous pouvez désormais connaître en temps réel le statut de votre dispositif mobile cellulaire. De plus, lorsque vous vous rendrez sur le site [estcequemonordinateurestallume.fr](https://estcequemonordinateurestallume.fr) ou [estcequemontelephoneestallume.fr](https://estcequemontelephoneestallume.fr), si l'appareil que vous utilisez en accédant aux sites n'est pas le bon, il vous sera proposé d'accéder directement au bon outil !

Au plaisir de pouvoir vous être utile !
